import "./globals.css";

import { FormProvider } from "../context/FormContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <FormProvider>{children}</FormProvider> */}
        {children}
      </body>
    </html>
  );
};
