
const formDataSchema = {
  project: {
    projectName: "",
    plotNo: undefined,
    village: "",
    taluka: "",
    district: "",
  },
  plot: {
    groupHousing: "",
    buildingType: {
      input: "",
      other: "",
      residential: undefined,
      commercial: undefined,
    },
    areaType: "",
    ulb: "",
    zone: "",
    plotType: "",
    proRata: undefined,
    builtUp: undefined,
    area: undefined,
    roadWidth: undefined,
  },
  fsi: {
    area: undefined,
    deductions: {
      proposedDp: undefined,
      anyDp: undefined,
      total: undefined,
    },
    balanceArea: undefined,
    aminitySpace: {
      required: undefined,
      adj2b: undefined,
      balanceProposed: undefined,
    },
    netPlotArea: undefined,
    recreationOpenSpace: {
      required: undefined,
      proposed: undefined,
    },
    internalRoadArea: undefined,
    plotableArea: undefined,
    builtUpArea: undefined,
    paymentOfPremium: {
      maxPremium: undefined,
      proposedPremium: undefined,
    },
    inSituLoading: {
      areaAgainstDpRoad: undefined,
      areaAgainstAminitySpace: undefined,
      tdrArea: undefined,
      toatlInSitu: undefined,
    },
    additinalFsi: undefined,
    totalEntitlementProposed: {
      whicheverApplicable: undefined,
      ancillaryArea: undefined,
      totalEntitlement: undefined,
    },
    maxUtilizationLimit: undefined,
    totalBuiltUpAreaProposal: {
      existingBuiltUpArea: undefined,
      proposedBuiltUpArea: undefined,
      totalBuiltUp: undefined,
    },
    FSIConsumed: undefined,
    areOfInclusiveHousing: {
      required: undefined,
      proposed: undefined,
    },
  },
};

const districts = [
  {
    name: "Ahmednagar",
    tahasil: [
      "Akola",
      "Jamkhed",
      "Karjat",
      "Kopargaon",
      "Nagar",
      "Nevasa",
      "Parner",
      "Pathardi",
      "Rahta",
      "Rahuri",
      "Sangamner",
      "Shevgaon",
      "Shrigonda",
      "Shrirampur",
    ],
  },

  {
    name: "Akola",
    tahasil: [
      "Akola",
      "Akot",
      "Balapur",
      "Barshitakli",
      "Murtijapur",
      "Patur",
      "Telhara",
    ],
  },
  {
    name: "Amravati",
    tahasil: [
      "Achalpur",
      "Amravati",
      "Anjangaon Surji",
      "Bhatkuli",
      "Chandur Railway",
      "Chandurbazar",
      "Chikhaldara",
      "Daryapur",
      "Dhamangaon Railway",
      "Dharni",
      "Morshi",
      "Nandgaon-Khandeshwar",
      "Teosa",
      "Warud",
    ],
  },

  {
    name: "Aurangabad",
    tahasil: [
      "Aurangabad",
      "Gangapur",
      "Kannad",
      "Khuldabad",
      "Paithan",
      "Phulambri",
      "Sillod",
      "Soegaon",
      "Vaijapur",
    ],
  },

  {
    name: "Beed",
    tahasil: [
      "Ambejogai",
      "Ashti",
      "Bid",
      "Dharur",
      "Georai",
      "Kaij",
      "Manjlegaon",
      "Parli",
      "Patoda",
      "Shirur (Kasar)",
      "Wadwani",
    ],
  },

  {
    name: "Bhandara",
    tahasil: ["Bhandara", "Mohadi", "Pauni", "Tumsar"],
  },

  {
    name: "Buldhana",
    tahasil: [
      "Buldana",
      "Chikhli",
      "Deolgaon Raja",
      "Jalgaon (Jamod)",
      "Khamgaon",
      "Lonar",
      "Malkapur",
      "Mehkar",
      "Motala",
      "Nandura",
      "Sangrampur",
      "Shegaon",
      "Sindkhed Raja",
    ],
  },

  {
    name: "Chandrapur",
    tahasil: [
      "Ballarpur",
      "Bhadravati",
      "Brahmapuri",
      "Chandrapur",
      "Chimur",
      "Gondpipri",
      "Jiwati",
      "Korpana",
      "Mul",
      "Nagbhir",
      "Pombhurna",
      "Rajura",
      "Sawali",
      "Sindewahi",
      "Warora",
    ],
  },

  {
    name: "Dhule",
    tahasil: ["Dhule", "Sakri", "Shirpur", "Sindkhede"],
  },

  {
    name: "Gadchiroli",
    tahasil: [
      "Aheri",
      "Armori",
      "Bhamragad",
      "Chamorshi",
      "Desaiganj (Vadasa)",
      "Dhanora",
      "Etapalli",
      "Gadchiroli",
      "Korchi",
      "Kurkheda",
      "Mulchera",
      "Sironcha",
    ],
  },

  {
    name: "Gondia",
    tahasil: [
      "Amgaon",
      "Arjuni Morgaon",
      "Deori",
      "Gondiya",
      "Goregaon",
      "Sadak-Arjuni",
      "Salekasa",
      "Tirora",
    ],
  },

  {
    name: "Hingoli",
    tahasil: ["Aundha (Nagnath)", "Basmath", "Hingoli", "Kalamnuri", "Sengaon"],
  },

  {
    name: "Jalgaon",
    tahasil: [
      "Amalner",
      "Bhadgaon",
      "Bhusawal",
      "Bodvad",
      "Chalisgaon",
      "Chopda",
      "Dharangaon",
      "Erandol",
      "Jalgaon",
      "Jamner",
      "Muktainagar",
      "Pachora",
      "Parola",
      "Raver",
      "Yawal",
    ],
  },

  {
    name: "Jalna",
    tahasil: [
      "Ambad",
      "Badnapur",
      "Bhokardan",
      "Ghansawangi",
      "Jafferabad",
      "Jalna",
      "Mantha",
      "Partur",
    ],
  },

  {
    name: "Kolhapur",
    tahasil: [
      "Ajra",
      "Bavda",
      "Bhudargad",
      "Chandgad",
      "Gadhinglaj",
      "Hatkanangle",
      "Kagal",
      "Karvir",
      "Panhala",
      "Radhanagari",
      "Shahuwadi",
      "Shirol",
    ],
  },

  {
    name: "Latur",
    tahasil: [
      "Ahmadpur",
      "Ausa",
      "Chakur",
      "Deoni",
      "Jalkot",
      "Latur",
      "Nilanga",
      "Renapur",
      "Shirur-Anantpal",
      "Udgir",
    ],
  },

  {
    name: "Mumbai Suburban",
    tahasil: ["Andheri", "Borivali", "Kurla"],
  },

  {
    name: "Nagpur",
    tahasil: [
      "Bhiwapur",
      "Hingna",
      "Kalameshwar",
      "Kamptee",
      "Katol",
      "Kuhi",
      "Mauda",
      "Nagpur (Rural)",
      "Nagpur (Urban)",
      "Narkhed",
      "Parseoni",
      "Ramtek",
      "Savner",
      "Umred",
    ],
  },

  {
    name: "Nanded",
    tahasil: [
      "Ardhapur",
      "Bhokar",
      "Biloli",
      "Deglur",
      "Dharmabad",
      "Hadgaon",
      "Himayatnagar",
      "Kandhar",
      "Kinwat",
      "Loha",
      "Mahoor",
      "Mudkhed",
      "Mukhed",
      "Naigaon (Khairgaon)",
      "Nanded",
      "Umri",
    ],
  },

  {
    name: "Nandurbar",
    tahasil: [
      "Akkalkuwa",
      "Akrani",
      "Nandurbar",
      "Nawapur",
      "Shahade",
      "Talode",
    ],
  },

  {
    name: "Nashik",
    tahasil: [
      "Baglan",
      "Chandvad",
      "Deola",
      "Dindori",
      "Igatpuri",
      "Kalwan",
      "Malegaon",
      "Nandgaon",
      "Nashik",
      "Niphad",
      "Peint",
      "Sinnar",
      "Surgana",
      "Trimbakeshwar",
      "Yevla",
    ],
  },

  {
    name: "Osmanabad",
    tahasil: [
      "Bhum",
      "Kalamb",
      "Lohara",
      "Osmanabad",
      "Paranda",
      "Tuljapur",
      "Umarga",
      "Washi",
    ],
  },

  {
    name: "Parbhani",
    tahasil: [
      "Gangakhed",
      "Jintur",
      "Manwath",
      "Palam",
      "Parbhani",
      "Pathri",
      "Purna",
      "Sailu",
      "Sonpeth",
    ],
  },

  {
    name: "Pune",
    tahasil: [
      "Ambegaon",
      "Baramati",
      "Bhor",
      "Daund",
      "Haveli",
      "Indapur",
      "Junnar",
      "Khed",
      "Mawal",
      "Mulshi",
      "Pune City",
      "Purandhar",
      "Shirur",
      "Velhe",
    ],
  },

  {
    name: "Raigad",
    tahasil: [
      "Alibag",
      "Karjat",
      "Khalapur",
      "Mahad",
      "Mangaon",
      "Mhasla",
      "Murud",
      "Panvel",
      "Pen",
      "Poladpur",
      "Roha",
      "Shrivardhan",
      "Sudhagad",
      "Tala",
      "Uran",
    ],
  },

  {
    name: "Ratnagiri",
    tahasil: [
      "Chiplun",
      "Dapoli",
      "Guhagar",
      "Khed",
      "Lanja",
      "Mandangad",
      "Rajapur",
      "Ratnagiri",
      "Sangameshwar",
    ],
  },

  {
    name: "Sangli",
    tahasil: [
      "Atpadi",
      "Jat",
      "Kadegaon",
      "Kavathemahankal",
      "Khanapur",
      "Miraj",
      "Palus",
      "Shirala",
      "Tasgaon",
      "Walwa",
    ],
  },

  {
    name: "Satara",
    tahasil: [
      "Jaoli",
      "Karad",
      "Khandala",
      "Khatav",
      "Koregaon",
      "Mahabaleshwar",
      "Man",
      "Patan",
      "Phaltan",
      "Satara",
      "Wai",
    ],
  },

  {
    name: "Sindhudurg",
    tahasil: [
      "Devgad",
      "Dodamarg",
      "Kankavli",
      "Kudal",
      "Malwan",
      "Sawantwadi",
      "Vaibhavvadi",
      "Vengurla",
    ],
  },

  {
    name: "Solapur",
    tahasil: [
      "Akkalkot",
      "Barshi",
      "Karmala",
      "Madha",
      "Malshiras",
      "Mangalvedhe",
      "Mohol",
      "Pandharpur",
      "Sangole",
      "Solapur North",
      "Solapur South",
    ],
  },

  {
    name: "Thane",
    tahasil: [
      "Ambarnath",
      "Bhiwandi",
      "Dahanu",
      "Jawhar",
      "Kalyan",
      "Mokhada",
      "Murbad",
      "Palghar",
      "Shahapur",
      "Talasari",
      "Thane",
      "Ulhasnagar",
      "Vada",
      "Vasai",
      "Vikramgad",
    ],
  },

  {
    name: "Washim",
    tahasil: [
      "Arvi",
      "Ashti",
      "Deoli",
      "Hinganghat",
      "Karanja",
      "Samudrapur",
      "Seloo",
      "Wardha",
    ],
  },

  {
    name: "Washim",
    tahasil: ["Karanja", "Malegaon", "Mangrulpir", "Manora", "Risod", "Washim"],
  },

  {
    name: "Yavatmal",
    tahasil: [
      "Arni",
      "Babulgaon",
      "Darwha",
      "Digras",
      "Ghatanji",
      "Kalamb",
      "Kelapur",
      "Mahagaon",
      "Maregaon",
      "Ner",
      "Pusad",
      "Ralegaon",
      "Umarkhed",
      "Wani",
      "Yavatmal",
      "Zari-Jamani",
    ],
  },
];

const formParkingSchema = {
  name: "",
  ulb: "",
  areaType: "",
  zone: "",
  buildingType: "",
  residential: {
    input: "",
    multi: {
      area150above: null,
      area80To150: null,
      area40To80: null,
      area30To40: null,
      areaLess30: null,
      above5PercentCar: null,
      above5PercentScooter: null,
      ulbForAboveCar: null,
      ulbForAboveScooter: null,
    },
    lodge: null,
    restaurants: null
  },
  institutional: null,
  publicGathering: {
    input: "",
    assembly: null,
    multiplex: null,
    mangalKaryalaya: null,
    communityHall: null
  },
  educational: {
    input: "",
    schools: {
      forEvery100sqm: null,
      forEvery3Classroom: null
    },
    college: {
      forEvery100sqm: null,
      forEvery3Classroom: null,
    },
    coaching: null
  },
  govOrPublicOrPrivate: {
    input: "",
    visitor: null,
  },
  mercantile: {
    input: "",
    marketStoresShops: null,
    wholeSale: null,
    hazardousBuilding: null,
    officeItBuilding: null,
  },
  industrial: null,
  storage: null,
  dataCentre: null,
};

const formPotentialFsiSchema = {
  projectName: "",
  buildingType: "",
  areaType: "",
  ulb: "",
  zone: "",
  plotType: "",
  proRata: undefined,
  builtUp: undefined,
  area: undefined,
  roadWidth: undefined,
};

const formBuildingMarginSchema = {
  projectName: "",
  buildingType: "",
  areaType: "",
  ulb: "",
  zone: "",
  moreThan500: undefined,
  buildingHeight: undefined,
  plotWidth: undefined,
  plotArea: undefined,
  plotType: "",
  roadDirection: {
    front: {
      input: "",
      roadWidth: ""
    },
    back: {
      input: "",
      roadWidth: ""
    },
    left: {
      input: "",
      roadWidth: ""
    },
    right: {
      input: "",
      roadWidth: ""
    },
  }
};

// const udcprIndex = [
//   //chapter 1
//   // {
//   //   no: '01',
//   //   title: 'Chapter-1 ADMINISTRATION',
//   //   page: 17,
//   //   subPoints: [
//   //     { no: '1.0', title: 'Short Title, Extent and Commencement', page: 17 },
//   //     { no: '1.1', title: 'Extent and Jurisdiction', page: 17 },
//   //     { no: '1.2', title: 'Commencement of regulation', page: 17 },
//   //     { no: '1.3', title: 'Definitions', page: 17 },
//   //     { no: '1.4', title: 'Applicability of Regulations', page: 32 },
//   //     { no: '1.5', title: 'Savings', page: 33 },
//   //     { no: '1.6', title: 'Applicability of Other Regulations', page: 34 },
//   //     { no: '1.7', title: 'Power to Prescribe the Proformas', page: 35 },
//   //     { no: '1.8', title: 'Power to Decide Charges', page: 35 },
//   //     { no: '1.9', title: 'Meanings as in Acts, Rules & Interpretations', page: 35 },
//   //     { no: '1.10', title: 'Removal of Difficulties', page: 36 },
//   //   ],
//   // },
//   // //chapter 2
//   // {
//   //   no: '02',
//   //   title: 'CHAPTER - 2 DEVELOPMENT PERMISSION AND COMMENCEMENT CERTIFICATE',
//   //   page: 37,
//   //   subPoints: [
//   //     { no: '2.1', title: 'Permission from the Planning Authority is Mandatory', page: 37 },
//   //     {
//   //       no: '2.1.1',
//   //       title: 'Necessity of Obtaining Permission',
//   //       page: 37,
//   //     },
//   //     { no: '2.1.2', title: 'Permission Not Necessary', page: 37 },
//   //     { no: '2.1.3', title: 'Development Undertaken on Behalf of Government', page: 38 },
//   //     { no: '2.1.4', title: 'Operational Constructions', page: 38 },
//   //     { no: '2.1.5', title: 'Constructions not Covered Under the Operational Constructions', page: 39 },
//   //     { no: '2.1.6', title: 'Temporary Constructions', page: 39 },
//   //     { no: '2.1.7', title: 'Repairs to Building', page: 40 },
//   //     {
//   //       no: '2.2',
//   //       title: 'Procedure for Obtaining Development Permission / Building Permission / Commencement Certificate',
//   //       page: 40,
//   //     },
//   //     { no: '2.2.1', title: 'Notice / Application', page: 40 },
//   //     { no: '2.2.2', title: 'Information Accompanying Notice / Application', page: 40 },
//   //     { no: '2.2.3', title: 'Ownership Title and Area', page: 40 },
//   //     { no: '2.2.4', title: 'Key Plan or Location Plan', page: 41 },
//   //     { no: '2.2.5 (a)', title: 'Sub-division Layout Plan', page: 41 },
//   //     { no: '2.2.5 (b)', title: 'Amalgamation Plan', page: 41 },
//   //     { no: '2.2.6', title: 'Site Plan', page: 42 },
//   //     { no: '2.2.7', title: 'Building Plan', page: 42 },
//   //     { no: '2.2.8', title: 'Building Plans for Special Buildings', page: 43 },
//   //     { no: '2.2.9', title: 'Service Plan', page: 44 },
//   //     { no: '2.2.10', title: 'Supervision', page: 44 },
//   //     { no: '2.2.11', title: 'Clearance From Other Departments', page: 44 },
//   //     { no: '2.2.12', title: 'Building / Layout Permission Scrutiny Fee', page: 45 },
//   //     { no: '2.2.13', title: 'Development Charges', page: 45 },
//   //     { no: '2.2.14', title: 'Premium Charges and Fire Infrastructure Charges', page: 46 },
//   //     { no: '2.2.15', title: 'Structural Stability Certificate', page: 47 },
//   //     { no: '2.2.16', title: 'Signing the Plan', page: 47 },
//   //     { no: '2.2.17', title: 'Size of Drawing Sheets', page: 48 },
//   //     { no: '2.2.18', title: 'Colouring Notations for Plans', page: 48 },
//   //     {
//   //       no: '2.2.19',
//   //       title: 'Qualification and Competence of the Architect / Licensed Engineer / Structural Engineer / Town Planner / Supervisor',
//   //       page: 49,
//   //     },
//   //     { no: '2.3', title: 'Discretionary Powers - Interpretation', page: 49 },
//   //     { no: '2.4', title: 'Discretionary Powers - Relaxations in Specific Cases', page: 49 },
//   //     { no: '2.5', title: 'Drafting Error', page: 50 },
//   //     { no: '2.6', title: 'Grant or Refusal of Permission', page: 50 },
//   //     { no: '2.6.1', title: 'General', page: 50 },
//   //     { no: '2.6.2', title: 'Deemed Permission', page: 50 },
//   //     { no: '2.6.3', title: 'Approval of building permission on Risk Based Classification', page: 51 },
//   //     { no: '2.6.4', title: 'Display of Sanctioned Permissions on Authority\'s Web-Site', page: 51 },
//   //     { no: '2.7', title: 'Commencement of Work', page: 51 },
//   //     { no: '2.7.1', title: 'Commencement', page: 51 },
//   //     { no: '2.7.2', title: 'Development of Land Subdivision / Group Housing Schemes', page: 52 },
//   //     { no: '2.8', title: 'Procedure During Construction', page: 52 },
//   //     {
//   //       no: '2.8.1',
//   //       title: 'Owner / Developer / Architect / Town Planner / Engineer / Structural Engineer / Supervisor or any licensed technical person\'s Responsibilities in Their Respective Domain',
//   //       page: 52,
//   //     },
//   //     { no: '2.8.2', title: 'Results of Test', page: 52 },
//   //     { no: '2.8.3', title: 'Display Board', page: 52 },
//   //     { no: '2.8.4', title: 'Plinth Checking', page: 53 },
//   //     { no: '2.8.5', title: 'Deviation during Construction', page: 53 },
//   //     { no: '2.9', title: 'Completion Certificate', page: 53 },
//   //     { no: '2.10', title: 'Occupancy Certificate', page: 53 },
//   //     { no: '2.11', title: 'Part Occupancy Certificate', page: 54 },
//   //     { no: '2.12', title: 'Inspection', page: 54 },
//   //     { no: '2.13', title: 'Unsafe Buildings', page: 54 },
//   //     { no: '2.14', title: 'Offences and Penalties', page: 54 },
//   //     { no: '2.15', title: 'Revocation of Permission', page: 54 },
//   //   ],
//   // },
//   // //chapter 3
//   // {
//   //   no:'03',
//   //   title: 'Chapter-3 GENERAL LAND DEVELOPMENT REQUIREMENTS ',
//   //   page: 57,
//   //   subPoints: [
//   //     { no: '3.1', title: 'Requirements of Site', page: 57 },
//   //     { no: '3.1.1', title: 'Site Not Eligible For Construction of Building', page: 57 },
//   //     { no: '3.1.2', title: 'Distance of Site From Electric Lines', page: 58 },
//   //     { no: '3.1.3', title: 'Construction Within Blue and Red Flood Line', page: 58 },
//   //     { no: '3.1.4', title: 'Development Within 30 m. Distance From Railway Boundary', page: 59 },
//   //     { no: '3.1.5', title: 'Environmental Clearance', page: 59 },
//   //     { no: '3.1.6', title: 'Development Along Highways / Classified Roads.', page: 59 },
//   //     { no: '3.1.7', title: 'Development Within Certain Distance from the Prison Premises', page: 59 },
//   //     { no: '3.1.8', title: 'Distances from Land Fill Sites', page: 59 },
//   //     { no: '3.1.9', title: 'Restrictions in the Vicinity of Airport', page: 59 },
//   //     { no: '3.1.10', title: 'Restrictions in the Vicinity of Ancient Monuments', page: 60 },
//   //     { no: '3.1.11', title: 'Restriction under the Works of Defense Act, 1903', page: 60 },
//   //     { no: '3.1.12', title: 'Distance from Natural Lake and Dam.', page: 60 },
//   //     { no: '3.1.13', title: 'Authorities to Supply Complete Information about Restrictions to the Authority', page: 61 },
//   //     { no: '3.2', title: 'Means of Access', page: 61 },
//   //     { no: '3.3', title: 'Regulations for Land Sub-division and Layout', page: 61 },
//   //     { no: '3.3.1', title: 'Obligation to Prepare Layout', page: 61 },
//   //     { no: '3.3.2', title: 'Roads / Streets in Land Sub-division or Layout', page: 62 },
//   //     { no: '3.3.3', title: 'Length of Internal Roads, How to be Measured', page: 63 },
//   //     { no: '3.3.4', title: 'Co-ordination of Roads in Adjoining Lands', page: 63 },
//   //     { no: '3.3.5', title: 'Narrow Roads in Congested Areas (Core area in case of Nashik Municipal Corporation)', page: 63 },
//   //     { no: '3.3.6', title: 'Development of Street', page: 63 },
//   //     { no: '3.3.7', title: 'Development of Private Street, if neglected', page: 63 },
//   //     { no: '3.3.8', title: 'Access from the Highways / Classified Roads', page: 63 },
//   //     { no: '3.3.9', title: 'Access Provision for Special Buildings of Regulation No.1.3(93)(xiv)', page: 64 },
//   //     { no: '3.3.10', title: 'Cul-de-sacs', page: 64 },
//   //     { no: '3.3.11', title: 'Handing Over of Layout Roads', page: 65 },
//   //     { no: '3.3.12', title: 'Intersection of Roads', page: 65 },
//   //     { no: '3.3.13', title: 'Acute Angled Junctions', page: 65 },
//   //     { no: '3.3.14', title: 'Land-locked Plot', page: 65 },
//   //     { no: '3.3.15', title: 'Approach by Underpass or Over Bride for Adjoining Properties.', page: 66 },
//   //     { no: '3.4', title: 'Recreational Open Spaces', page: 66 },
//   //     { no: '3.4.1', title: 'Recreational Open Space', page: 66 },
//   //     { no: '3.4.2', title: 'Recreational Open Space - Owner’s Undertaking', page: 67 },
//   //     { no: '3.4.3', title: 'Recreational Open Space - Rearrangement', page: 68 },
//   //     { no: '3.4.4', title: 'Recreational Open Space - Exclusive', page: 68 },
//   //     { no: '3.4.5', title: 'Recreational Open Space in Green Belt', page: 68 },
//   //     { no: '3.4.6', title: 'Minimum Dimensions', page: 68 },
//   //     { no: '3.4.7', title: 'Structures Permitted in Open Space', page: 68 },
//   //     { no: '3.4.8', title: 'Recreational Open Space and Means of Access', page: 69 },
//   //     { no: '3.5', title: 'Provision for Amenity Space', page: 69 },
//   //     { no: '3.5.1', title: 'In the areas of Local Authorities, Special Planning Authorities and Metropolitan Region Authorities', page: 69 },
//   //     { no: '3.5.2', title: 'In case of Regional Plan Areas.', page: 70 },
//   //     { no: '3.5.3', title: 'Development of Amenity Spaces in Earlier Sanctioned Layout', page: 70 },
//   //     { no: '3.6', title: 'Provision for Electric Sub-station', page: 71 },
//   //     { no: '3.7', title: 'Minimum Plot Area for Various Uses', page: 71 },
//   //     { no: '3.8', title: 'Provision for Inclusive Housing', page: 72 },
//   //     { no: '3.9', title: 'Net Plot Area and Computation of FSI', page: 75 },
//   //     { no: '3.10', title: 'Transfer of DP Sites (other than DP road) in lieu of FSI', page: 75 },
//   //     { no: '3.11', title: 'Relocation of DP-RP Sites / Roads', page: 75 },
//   //     { no: '3.12', title: 'Amalgamation of Plots', page: 76 },
//   //     { no: '3.13', title: 'Development of Cycle Track Along River and Nallah', page: 76 },
//   //     { no: '3.13.1', title: 'For Nashik Municipal Corporation.', page: 76 },
//   //     { no: '3.13.2', title: 'For Other Municipal Corporations.', page: 76 }
//   //   ]
//   // },
//   // //chapter 4
//   // {
//   //     no: '04',
//   //     title: 'Chapter-4 LAND USE CLASSIFICATION AND PERMISSIBLE USES',
//   //     page: 77,
//   //     subPoints: [
//   //       { no: '4.1', title: 'General', page: 77 },
//   //       { no: '4.2', title: 'Land Use Classification and Equivalency of Zones', page: 77 },
//   //       { no: '4.3', title: 'Residential Zone - R-1', page: 79 },
//   //       { no: '4.4', title: 'Residential Zone - R-2', page: 81 },
//   //       { no: '4.5', title: 'Low Density Residential Zone', page: 83 },
//   //       { no: '4.6', title: 'Future Urbanisable Zone', page: 83 },
//   //       { no: '4.7', title: 'Commercial Zone', page: 83 },
//   //       { no: '4.8', title: 'Industrial Zone', page: 83 },
//   //       { no: '4.8.1', title: 'Allowing Residential / Commercial Uses in Industrial Zone', page: 84 },
//   //       { no: '4.9', title: 'Loom Industry cum Residential Zone', page: 87 },
//   //       { no: '4.10', title: 'Public / Semi Public Zone', page: 87 },
//   //       { no: '4.11', title: 'Agricultural Zone', page: 88 },
//   //       { no: '4.12', title: 'Green Belt Zone / River Protection Belt', page: 94 },
//   //       { no: '4.13', title: 'Traffic and Transportation Zone', page: 94 },
//   //       { no: '4.14', title: 'Regional Park Zone', page: 94 },
//   //       { no: '4.15', title: 'Tourism Development Zone', page: 95 },
//   //       { no: '4.16', title: 'Afforestation Zone', page: 95 },
//   //       { no: '4.17', title: 'Hill Top - Hill Slope Zone / Hilly Area', page: 95 },
//   //       { no: '4.18', title: 'Green Zone-2', page: 95 },
//   //       { no: '4.19', title: 'Forest Zone', page: 95 },
//   //       { no: '4.20', title: 'Defense Zone', page: 95 },
//   //       { no: '4.21', title: 'Mines and Quarry Zone', page: 96 },
//   //       { no: '4.22', title: 'Public Utility Zone', page: 96 },
//   //       { no: '4.23', title: 'Woodland Corridor', page: 96 },
//   //       { no: '4.24', title: 'Special Economic Zone', page: 96 },
//   //       { no: '4.25', title: 'Airport and Allied Activities / Service Zone', page: 96 },
//   //       { no: '4.26', title: 'Additional Uses', page: 97 },
//   //       { no: '4.27', title: 'Uses Permissible in Development Plan Reservations', page: 97 }
//   //   ]
//   // },
//   // //chapter 5
//   // {
//   //   no: '05',
//   //   title: 'Chapter-5 ADDITIONAL PROVISIONS FOR REGIONAL PLAN AREAS',
//   //   page: 101,
//   //   subPoints: [
//   //     { no: '005', title: 'CHAPTER - 5 ADDITIONAL PROVISIONS FOR REGIONAL PLAN AREAS', page: 101 },
//   //     { no: '5.0', title: 'General', page: 101 },
//   //     { no: '5.1', title: 'For all Regional Plan Areas', page: 101 },
//   //     { no: '5.1.1', title: 'Development Permissible Adjacent to Gaothan', page: 101 },
//   //     { no: '5.1.2', title: 'Regulations for Development of Tourist Resorts / Holiday Homes / Township in Hill Stations Type Areas under Hill Station Policy', page: 102 },
//   //     { no: '5.1.3', title: 'Committed Development', page: 102 },
//   //     { no: '5.1.4', title: 'Rectification of Draftsman\'s Error', page: 102 },
//   //     { no: '5.1.5', title: 'Highways notified by State / Central Government', page: 103 },
//   //     { no: '5.1.6', title: 'Station Area Development', page: 103 },
//   //     { no: '5.1.7', title: 'Modification Proposals Already Sanctioned', page: 103 },
//   //     { no: '5.1.8', title: 'Provision of Amenity Space', page: 103 },
//   //     { no: '5.1.9', title: 'Residential Zone with Payment of Premium', page: 104 },
//   //     { no: '5.2', title: 'For Thane - Raigad - Palghar Regional Plan', page: 104 },
//   //     { no: '5.2.1', title: 'Development in Tarapur - Boisar Area', page: 104 },
//   //     { no: '5.3', title: 'For Ratnagiri - Sindhudurg Regional Plan', page: 105 },
//   //     { no: '5.3.1', title: 'Area within Ratnagiri District', page: 105 },
//   //     { no: '5.3.2', title: 'Area within Sindhudurg District', page: 105 },
//   //     { no: '5.4', title: 'For Kolhapur Regional Plan', page: 107 },
//   //     { no: '5.5', title: 'For Satara Regional Plan', page: 108 },
//   //     { no: '5.6', title: 'For Hingoli, Buldhana, Washim, Yawatmal, Nanded Regional Plan', page: 117 },
//   //     { no: '5.7', title: 'For Raigad Regional Plan', page: 118 },
//   //     { no: '5.8', title: 'For Solapur Regional Plan', page: 118 },
//   //     { no: '5.9', title: 'For Pune Regional Plan', page: 118 },
//   //     { no: '5.10', title: 'Certain Regulations cease to operate in future', page: 120 },
//   //     { no: '5.11', title: 'Board of Appeals', page: 120 },
//   //     { no: '5.12', title: 'Aurangabad Regional Plan', page: 121 }
//   // ]
//   // },
//   // //chapter 6
//   // {
//   //   no: '06',
//   //   title: 'Chapter 6 - GENERAL BUILDING REQUIREMENTS - SETBACK, MARGINAL DISTANCE, HEIGHT AND PERMISSIBLE FSI',
//   //   page: 123,
//   //   subPoints: [
//   //       { no: '6.0', title: 'General', page: 123 },
//   //       { no: '6.1', title: 'Regulations for Congested Area in Development Plans / Gaothan of Village Settlements in Metropolitan Region Development Authorities and Regional Plans', page: 123 },
//   //       { no: '6.1.1', title: 'Residential Buildings / Residential Buildings with mixed-use', page: 123 },
//   //       { no: '6.1.2', title: 'Other buildings like Public / Semi-Public, Educational, Medical, Institutional, Commercial, Mercantile, etc.', page: 125 },
//   //       { no: '6.1.3', title: 'Width of Pathway', page: 125 },
//   //       { no: '6.1.4', title: 'Front Setback', page: 125 },
//   //       { no: '6.2', title: 'Regulations for Outside Congested Area (Non-Congested Area)', page: 125 },
//   //       { no: '6.2.1', title: 'Marginal Distances and Set-back for Residential Buildings and Mixed Use', page: 125 },
//   //       { no: '6.2.2', title: 'Other Building', page: 128 },
//   //       { no: '6.2.3', title: 'Marginal Distances for Buildings of Higher Heights', page: 132 },
//   //       { no: '6.2.4', title: 'In the cases of layouts of two or more buildings in a plot for any uses', page: 133 },
//   //       { no: '6.2.5', title: 'In case of group housing scheme', page: 133 },
//   //       { no: '6.2.6', title: 'Building Abutting Two or More Streets', page: 133 },
//   //       { no: '6.3', title: 'Permissible FSI', page: 133 },
//   //       { no: '6.4', title: 'Industrial Buildings', page: 137 },
//   //       { no: '6.5', title: 'FSI of Green Belt', page: 137 },
//   //       { no: '6.6', title: 'Calculation of Built-up area for the Purposes of FSI', page: 138 },
//   //       { no: '6.7', title: 'Permissible Projections in Marginal Open Spaces / Distances', page: 138 },
//   //       { no: '6.8', title: 'Exclusion of Structures / Projections for FSI Calculation', page: 139 },
//   //       { no: '6.9', title: 'Interior and Exterior chowk', page: 140 },
//   //       { no: '6.10', title: 'Height of Building', page: 140 },
//   //       { no: '6.11', title: 'Height Exemptions', page: 141 },
//   //       { no: '6.12', title: 'Requirements in case of Building more than 70 m Height', page: 141 },
//   //       { no: '6.13', title: 'FSI of Lands Affected by HEMRL or Other Restrictions', page: 141 },
//   //       { no: '6.14', title: 'Provision of Recreational Floor', page: 141 }
//   //   ],
//   // },
//   // //chapter 7
//   // {
//   //   no: '07',
//   //   title: 'CHAPTER - 7 HIGHER FSI FOR CERTAIN USES',
//   //   page: 143,
//   //   subPoints: [
//   //       { no: '7.0', title: 'General', page: 143 },
//   //       { no: '7.1', title: '* Higher F.S.I.', page: 144 },
//   //       { no: '7.2', title: 'Entitlement of FSI for Road Widening or Construction of New Roads / Surrender of Reserved Land', page: 147 },
//   //       { no: '7.3', title: 'Development / Redevelopment of Staff Quarters of the State Government or its Statutory Bodies or Planning Authority', page: 147 },
//   //       { no: '7.4', title: '* Development / Redevelopment of Housing Schemes of Maharashtra Housing and Area Development Authority', page: 149 },
//   //       { no: '7.5', title: 'Protection of FSI in Redevelopment of Existing Buildings', page: 152 },
//   //       { no: '7.6', title: 'Redevelopment of Old Dilapidated / Dangerous Buildings', page: 152 },
//   //       { no: '7.6.1', title: 'Redevelopment of Multi-dwelling Buildings of Owner / Owners', page: 153 },
//   //       { no: '7.6.2', title: 'Redevelopment of Tenanted Buildings', page: 153 },
//   //       { no: '7.7', title: 'Development of Housing for EWS / LIG', page: 154 },
//   //       { no: '7.8', title: 'Regulations for Development of Information Technology Establishment', page: 155 },
//   //       { no: '7.8.1', title: 'For Municipal Corporation, Area Development Authority and Special Planning Authority Area', page: 155 },
//   //       { no: '7.8.2', title: 'For Municipal Council, Nagar Panchayat and Non-Municipal Town Development Plan Area', page: 157 },
//   //       { no: '7.8.3', title: 'For Regional Plan Area', page: 157 },
//   //       { no: '7.9', title: 'Regulation for Development of Biotechnology Parks', page: 158 },
//   //       { no: '7.10', title: '* Incentive for Green Buildings', page: 159 },
//   //       { no: '7.11', title: 'Development of Public Toilet', page: 160 },
//   //       { no: '7.12', title: 'Buildings of Smart Fin-Tech Centre', page: 160 },
//   //       { no: '7.13', title: 'Commercial Building in CBD, Commercial, Residential Zone in Planning Authorities Area', page: 161 },
//   //   ]
//   // },
//   // //chapter 8
//   // {
//   //   no: '08',
//   //   title: 'Chapter-8 PARKING LOADING AND UNLOADING SPACES',
//   //   page: 163,
//   //   subPoints: [
//   //     { no: '8.1', title: 'Parking Spaces', page: 163 },
//   //     { no: '8.2', title: 'Off Street Parking Requirement ', page: 164 },
//   //     { no: '8.2.1', title: 'Off Street Parking Requirement ', page: 164 },
//   //     { no: '8.2.2', title: 'Off Street Parking Requirement for Various Planning Authorities / Areas', page: 170 },
      
//   //   ],
//   // },
//   // //chapter 9
//   // {
//   //   no: '09',
//   //   title: 'CHAPTER - 9 REQUIREMENTS OF PART OF BUILDING',
//   //   page: 171,
//   //   subPoints: [
//   //       { no: '9.0', title: 'Standard Requirement of Various Parts of Buildings', page: 171 },
//   //       { no: '9.1', title: 'Plinth', page: 171 },
//   //       { no: '9.2', title: 'Habitable Rooms', page: 171 },
//   //       { no: '9.3', title: 'Kitchen', page: 172 },
//   //       { no: '9.4', title: 'Bath Rooms, Water Closets, Combined Bath Room and Water Closet', page: 172 },
//   //       { no: '9.5', title: 'Ledge or Tand / Loft', page: 172 },
//   //       { no: '9.6', title: 'Cupboard', page: 173 },
//   //       { no: '9.7', title: '* Mezzanine Floor', page: 173 },
//   //       { no: '9.8', title: 'Store Room', page: 174 },
//   //       { no: '9.9', title: 'Garage', page: 174 },
//   //       { no: '9.10', title: 'Roofs', page: 174 },
//   //       { no: '9.11', title: 'Basements', page: 175 },
//   //       { no: '9.12', title: '* Ramp', page: 176 },
//   //       { no: '9.13', title: '# Podium', page: 176 },
//   //       { no: '9.14', title: 'Balcony', page: 177 },
//   //       { no: '9.15', title: 'Supported Double Height Terraces', page: 177 },
//   //       { no: '9.16', title: 'Stilt', page: 177 },
//   //       { no: '9.17', title: 'Chimneys', page: 177 },
//   //       { no: '9.18', title: 'Letter Box', page: 178 },
//   //       { no: '9.19', title: 'Meter Room', page: 178 },
//   //       { no: '9.20', title: 'Lighting and Ventilation of Room', page: 178 },
//   //       { no: '9.21', title: 'Overhead Tanks', page: 179 },
//   //       { no: '9.22', title: 'Parapet', page: 179 },
//   //       { no: '9.23', title: 'Cabin', page: 179 },
//   //       { no: '9.24', title: 'Wells', page: 179 },
//   //       { no: '9.25', title: 'Septic Tanks', page: 179 },
//   //       { no: '9.26', title: 'Boundary / Compound Wall', page: 179 },
//   //       { no: '9.27', title: '# Provision of Lift', page: 180 },
//   //       { no: '9.28', title: '* # Exit Requirements', page: 180 },
//   //       { no: '9.29', title: '* Other Requirements of Individual Exit at Each Floor', page: 183 },
//   //       { no: '9.30', title: 'Architectural Projections', page: 187 },
//   //       { no: '9.31', title: '* Additional Requirements in case of Housing Schemes', page: 187 },
//   //       { no: '9.32', title: 'Fire Protection Requirement', page: 187 },
//   //       { no: '9.33', title: 'Service Floor', page: 188 },
//   //   ]
//   // },
//   // //chapter 10
//   // {
//   //   no: '10',
//   //   title: 'CHAPTER - 10 CITY SPECIFIC REGULATIONS',
//   //   page: 189,
//   //   subPoints: [
//   //       { no: '10.0', title: 'General', page: 189 },
//   //       { no: '10.1', title: 'Pune City Municipal Corporation.', page: 189 },
//   //       { no: '10.2', title: '* Thane Municipal Corporation area.', page: 192 },
//   //       { no: '10.3', title: 'Nagpur Municipal Corporation', page: 198 },
//   //       { no: '10.4', title: '* # Nagpur Metropolitan Region Development Authority', page: 199 },
//   //       { no: '10.5', title: '* Nashik Municipal Corporation', page: 202 },
//   //       { no: '10.6', title: 'Vasai-Virar City Municipal Corporation', page: 203 },
//   //       { no: '10.7', title: 'Mira-Bhayandar Municipal Corporation', page: 203 },
//   //       { no: '10.8', title: 'Ulhasnagar City Municipal Corporation', page: 203 },
//   //       { no: '10.9', title: '* Kolhapur Municipal Corporation', page: 203 },
//   //       { no: '10.10', title: '# Navi Mumbai Municipal Corporation', page: 209 },
//   //       { no: '10.11', title: 'National Park and Tungareshwar Eco Sensitive Zone.', page: 215 },
//   //       { no: '10.12', title: 'Maharashtra Airport Development Company Notified Area.', page: 215 },
//   //       { no: '10.13', title: 'Bhiwandi Surrounding Notified Area', page: 215 },
//   //       { no: '10.14', title: 'CIDCO Area Excluding NAINA Area', page: 219 },
//   //       { no: '10.14 A', title: 'CIDCO Area within Panvel Municipal Corporation', page: 221 },
//   //       { no: '10.15', title: '* Certain Regulations Cease to Operate in Future.', page: 221 },
//   //   ]
//   // },
//   // //chapter 11
//   // {
//   //   no: '11',
//   //   title: 'ACQUISITION AND DEVELOPMENT OF RESERVED SITES IN DEVELOPMENT PLANS',
//   //   page: 223,
//   //   subPoints: [
//   //       { no: '11.0', title: 'General', page: 223 },
//   //       { no: '11.1', title: 'Manner of Development of Reserved Site in Development Plan (Accommodation Reservation Principle)', page: 223 },
//   //       { no: '11.2', title: 'Regulations for Grant of Transferable Development Rights', page: 237 },
//   //       { no: '11.2.1', title: 'Transferable Development Rights', page: 237 },
//   //       { no: '11.2.2', title: 'Cases Eligible for Transferable Development Rights (TDR)', page: 237 },
//   //       { no: '11.2.3', title: 'Cases not Eligible for Transferable Development Rights (TDR)', page: 237 },
//   //       { no: '11.2.4', title: 'Generation of the Transferable Development Rights (TDR)', page: 238 },
//   //       { no: '11.2.5', title: 'Transferable Development Rights (TDR) against Construction of Amenity', page: 239 },
//   //       { no: '11.2.6', title: 'Utilisation of Transferable Development Rights (TDR)', page: 240 },
//   //       { no: '11.2.7', title: 'Utilisation of Transferable Development Rights (TDR) and Road Width Relation', page: 240 },
//   //       { no: '11.2.8', title: 'Areas Restricted from Utilisation of Transferable Development Rights (TDR)', page: 240 },
//   //       { no: '11.2.9', title: 'General Stipulation', page: 241 },
//   //       { no: '11.2.10', title: 'Transfer of DRC', page: 241 },
//   //       { no: '11.2.11', title: 'Infrastructure Improvement Charges', page: 242 },
//   //       { no: '11.2.12', title: 'Vesting of Land', page: 242 },
//   //       { no: '11.2.13', title: 'Effect of this Regulation', page: 242 },
//   //       { no: '11.3', title: 'Reservation Credit Certificate (RCC)', page: 242 },
//   //   ],
//   // },
//   // //chapter 12
//   // {
//   //   no: '12',
//   //   title: 'STRUCTURAL SAFETY, WATER SUPPLY, DRAINAGE AND SANITARY REQUIREMENTS, OUTDOOR DISPLAY AND OTHER SERVICES',
//   //   page: 245,
//   //   subPoints: [
//   //       { no: '12.1', title: 'Structural Design', page: 245 },
//   //       { no: '12.2', title: 'Quality of Materials and Workmanship', page: 245 },
//   //       { no: '12.3', title: 'Alternative Materials, Methods of Design & Construction and Tests', page: 245 },
//   //       { no: '12.4', title: 'Building Services', page: 246 },
//   //       { no: '12.5', title: 'Water Supply, Drainage and Sanitary Requirements', page: 246 },
//   //       { no: '12.6', title: 'Drainage and Sanitation Requirements', page: 248 },
//   //       { no: '12.6.1', title: 'General', page: 248 },
//   //       { no: '12.6.2', title: 'For Residences', page: 248 },
//   //       { no: '12.6.3', title: 'For Buildings other than Residences', page: 248 },
//   //       { no: '12.7', title: 'Signs and Outdoor Display Structures', page: 249 },
//   //   ],
//   // },
//   // //chapter 13
//   // {
//   //   no: '13',
//   //   title: 'SPECIAL PROVISIONS FOR CERTAIN BUILDINGS',
//   //   page: 255,
//   //   subPoints: [
//   //       { no: '13.0', title: 'General', page: 255 },
//   //       { no: '13.1', title: 'Provisions for Barrier Free Access', page: 255 },
//   //       { no: '13.1.1', title: 'Definitions', page: 255 },
//   //       { no: '13.1.2', title: 'Scope', page: 255 },
//   //       { no: '13.1.3', title: 'Site Development', page: 255 },
//   //       { no: '13.1.4', title: 'Building Requirements', page: 256 },
//   //       { no: '13.2', title: 'Installation of Solar Assisted Water Heating (SWH) System / Roof Top Photovoltaic (RTPV) System', page: 258 },
//   //       { no: '13.3', title: 'Rain Water Harvesting', page: 259 },
//   //       { no: '13.4', title: 'Grey Water Recycling and Reuse', page: 260 },
//   //       { no: '13.5', title: 'Solid Waste Management', page: 262 },
//   //   ],
//   // },
//   // //chapter 14
//   // {
//   //   no: '14',
//   //   title: 'SPECIAL SCHEMES',
//   //   page: 263,
//   //   subPoints: [
//   //       { no: '14.1', title: 'Integrated Township Project (ITP)', page: 263 },
//   //       { no: '14.1.1', title: '* For Regional Plan Area', page: 263 },
//   //       { no: '14.1.2', title: 'For Development Plan Area', page: 279 },
//   //       { no: '14.2', title: 'Transit Oriented Development (TOD)', page: 280 },
//   //       { no: '14.2.1', title: '# For Pune Municipal Corporation Area', page: 281 },
//   //       { no: '14.2.2', title: 'Pune Metropolitan Region Development Authority area.', page: 285 },
//   //       { no: '14.2.3', title: '* For Nagpur Municipal Corporation and Nagpur Metropolitan Region Development Authority.', page: 285 },
//   //       { no: '14.2.4', title: 'For Other Municipal Corporations and Other Metropolitan Region Development Authority Area', page: 290 },
//   //       { no: '14.2.5', title: 'Regulations for BRT Corridor in Pimpri-Chinchwad Municipal Corporation.', page: 290 },
//   //       { no: '14.3', title: '* Affordable Housing Scheme', page: 291 },
//   //       { no: '14.4', title: 'Pradhan Mantri Awas Yojana', page: 294 },
//   //       { no: '14.4.1', title: '# For Development Plan Area.', page: 294 },
//   //       { no: '14.4.2', title: 'For Regional Plan Area.', page: 295 },
//   //       { no: '14.5', title: 'Conservation of Heritage Buildings / Precincts / Natural Features', page: 295 },
//   //       { no: '14.6', title: 'Slum Rehabilitation Scheme for Pune, PCMC, PCNTDA and Nagpur.', page: 301 },
//   //       { no: '14.7', title: '* Slum Rehabilitation Scheme for Other Municipal Corporations.', page: 334 },
//   //       { no: '14.8', title: '* # Urban Renewal Scheme', page: 348 },
//   //       { no: '14.9', title: 'Development of Tourism and Hospitality Services under Community Nature Conservancy Around Wild Life Sanctuaries and National Parks.', page: 365 },
//   //       { no: '14.10', title: 'Integrated Information Technology Township (IITP)', page: 366 },
//   //       { no: '14.11', title: 'Integrated Logistic Park (ILP)', page: 370 },
//   //       { no: '14.12', title: 'Industrial Township Under Aerospace and Defense Manufacturing Policy', page: 373 },
//   //       { no: '14.13', title: 'Development of Integrated Industrial Area', page: 373 },
//   //   ],
//   // },
//   // //chapter 15
//   // {
//   //   no: '15',
//   //   title: 'REGULATIONS FOR SPECIAL ACTIVITIES / PLANS',
//   //   page: 375,
//   //   subPoints: [
//   //       { no: '15.1', title: 'Quarrying Operations', page: 375 },
//   //       { no: '15.2', title: '*** Erection of Mobile Towers', page: 375 },
//   //       { no: '15.3', title: 'Preparation of Local Area Plan', page: 376 },
//   //       { no: '15.4', title: '* Guidelines for Street Design in City / Town.', page: 376 },
//   //   ],
//   // },
// ];

const udcprIndex = [
  {
    chapter: "CHAPTER - 1",
    title: "ADMINISTRATION",
    sections: [
      { subchapter: "1.0", title: "Short Title, Extent and Commencement", page: 1 },
      { subchapter: "1.1", title: "Extent and Jurisdiction", page: 1 },
      { subchapter: "1.2", title: "Commencement of Regulations", page: 1 },
      { subchapter: "1.3", title: "Definitions", page: 1 },
      { subchapter: "1.4", title: "Applicability of Regulations", page: 16 },
      { subchapter: "1.5", title: "Saving", page: 17 },
      { subchapter: "1.6", title: "Applicability of Other Regulations", page: 18 },
      { subchapter: "1.7", title: "Power to Prescribe the Proformas", page: 19 },
      { subchapter: "1.8", title: "Power to Decide Charges", page: 19 },
      { subchapter: "1.9", title: "Meanings as in Acts, Rules & Interpretations", page: 19 },
      { subchapter: "1.10", title: "Removal of Difficulties", page: 20 }
    ]
  },
  {
    chapter: "CHAPTER - 2",
    title: "DEVELOPMENT PERMISSION AND COMMENCEMENT CERTIFICATE",
    sections: [
      { subchapter: "2.1", title: "Permission from the Planning Authority is Mandatory", page: 21 },
      { subchapter: "2.1.1", title: "Necessity of Obtaining Permission", page: 21 },
      { subchapter: "2.1.2", title: "Permission Not Necessary", page: 21 },
      { subchapter: "2.1.3", title: "Development Undertaken on Behalf of Government", page: 22 },
      { subchapter: "2.1.4", title: "Operational Constructions", page: 22 },
      { subchapter: "2.1.5", title: "Constructions not Covered Under the Operational Constructions", page: 23 },
      { subchapter: "2.1.6", title: "Temporary Constructions", page: 23 },
      { subchapter: "2.1.7", title: "Repairs to Building", page: 24 },
      { subchapter: "2.2", title: "Procedure for Obtaining Development Permission / Building Permission / Commencement Certificate", page: 24 },
      { subchapter: "2.2.1", title: "Notice / Application", page: 24 },
      { subchapter: "2.2.2", title: "Information Accompanying Notice / Application", page: 24 },
      { subchapter: "2.2.3", title: "Ownership Title and Area", page: 24 },
      { subchapter: "2.2.4", title: "Key Plan or Location Plan", page: 25 },
      { subchapter: "2.2.5 (a)", title: "Sub-division Layout Plan", page: 25 },
      { subchapter: "2.2.5 (b)", title: "Amalgamation Plan", page: 25 },
      { subchapter: "2.2.6", title: "Site Plan", page: 26 },
      { subchapter: "2.2.7", title: "Building Plan", page: 26 },
      { subchapter: "2.2.8", title: "Building Plans for Special Buildings", page: 27 },
      { subchapter: "2.2.9", title: "Service Plan", page: 28 },
      { subchapter: "2.2.10", title: "Supervision", page: 28 },
      { subchapter: "2.2.11", title: "Clearance From Other Departments", page: 28 },
      { subchapter: "2.2.12", title: "Building / Layout Permission Scrutiny Fee", page: 29 },
      { subchapter: "2.2.13", title: "Development Charges", page: 29 },
      { subchapter: "2.2.14", title: "Premium Charges and Fire Infrastructure Charges", page: 30 },
      { subchapter: "2.2.15", title: "Structural Stability Certificate", page: 31 },
      { subchapter: "2.2.16", title: "Signing the Plan", page: 31 },
      { subchapter: "2.2.17", title: "Size of Drawing Sheets", page: 32 },
      { subchapter: "2.2.18", title: "Colouring Notations for Plans", page: 32 },
      { subchapter: "2.2.19", title: "Qualification and Competence of the Architect / Licensed Engineer / Structural Engineer / Town Planner / Supervisor", page: 33 },
      { subchapter: "2.3", title: "Discretionary Powers - Interpretation", page: 33 },
      { subchapter: "2.4", title: "Discretionary Powers - Relaxations in Specific Cases", page: 33 },
      { subchapter: "2.5", title: "Drafting Error", page: 34 },
      { subchapter: "2.6", title: "Grant or Refusal of Permission", page: 34 },
      { subchapter: "2.6.1", title: "General", page: 34 },
      { subchapter: "2.6.2", title: "Deemed Permission", page: 34 },
      { subchapter: "2.6.3", title: "Approval of Building Permission on Risk Based Classification", page: 35 },
      { subchapter: "2.6.4", title: "Display of Sanctioned Permissions on Authority's Website", page: 35 },
      { subchapter: "2.7", title: "Commencement of Work", page: 35 },
      { subchapter: "2.7.1", title: "Commencement", page: 35 },
      { subchapter: "2.7.2", title: "Development of Land Subdivision / Group Housing Schemes", page: 36 },
      { subchapter: "2.8", title: "Procedure During Construction", page: 36 },
      { subchapter: "2.8.1", title: "Owner / Developer / Architect / Town Planner / Engineer / Structural Engineer / Supervisor Responsibilities", page: 36 },
      { subchapter: "2.8.2", title: "Results of Test", page: 36 },
      { subchapter: "2.8.3", title: "Display Board", page: 36 },
      { subchapter: "2.8.4", title: "Plinth Checking", page: 37 },
      { subchapter: "2.8.5", title: "Deviation during Construction", page: 37 },
      { subchapter: "2.9", title: "Completion Certificate", page: 37 },
      { subchapter: "2.10", title: "Occupancy Certificate", page: 37 },
      { subchapter: "2.11", title: "Part Occupancy Certificate", page: 38 },
      { subchapter: "2.12", title: "Inspection", page: 38 },
      { subchapter: "2.13", title: "Unsafe Buildings", page: 38 },
      { subchapter: "2.14", title: "Offences and Penalties", page: 38 },
      { subchapter: "2.15", title: "Revocation of Permission", page: 39 }
    ]
  },
  {
    chapter: "CHAPTER - 3",
    title: "GENERAL LAND DEVELOPMENT REQUIREMENTS",
    sections: [
      { subchapter: "3.1", title: "Requirements of Site", page: 41 },
      { subchapter: "3.1.1", title: "Site Not Eligible For Construction of Building", page: 41 },
      { subchapter: "3.1.2", title: "Distance of Site From Electric Lines", page: 42 },
      { subchapter: "3.1.3", title: "Construction Within Blue and Red Flood Line", page: 42 },
      { subchapter: "3.1.4", title: "Development Within 30 m. Distance From Railway Boundary", page: 43 },
      { subchapter: "3.1.5", title: "Environmental Clearance", page: 43 },
      { subchapter: "3.1.6", title: "Development Along Highways / Classified Roads", page: 43 },
      { subchapter: "3.1.7", title: "Development Within Certain Distance from the Prison Premises", page: 43 },
      { subchapter: "3.1.8", title: "Distances from Land Fill Sites", page: 43 },
      { subchapter: "3.1.9", title: "Restrictions in the Vicinity of Airport", page: 43 },
      { subchapter: "3.1.10", title: "Restrictions in the Vicinity of Ancient Monuments", page: 44 },
      { subchapter: "3.1.11", title: "Restriction under the Works of Defense Act, 1903", page: 44 },
      { subchapter: "3.1.12", title: "Distance from Natural Lake and Dam", page: 44 },
      { subchapter: "3.1.13", title: "Authorities to Supply Complete Information about Restrictions to the Authority", page: 45 },
      { subchapter: "3.2", title: "Means of Access", page: 45 },
      { subchapter: "3.3", title: "Regulations for Land Sub-division and Layout", page: 45 },
      { subchapter: "3.3.1", title: "Obligation to Prepare Layout", page: 45 },
      { subchapter: "3.3.2", title: "Roads / Streets in Land Sub-division or Layout", page: 46 },
      { subchapter: "3.3.3", title: "Length of Internal Roads, How to be Measured", page: 47 },
      { subchapter: "3.3.4", title: "Co-ordination of Roads in Adjoining Lands", page: 47 },
      { subchapter: "3.3.5", title: "Narrow Roads in Congested Areas", page: 47 },
      { subchapter: "3.3.6", title: "Development of Street", page: 47 },
      { subchapter: "3.3.7", title: "Development of Private Street, if Neglected", page: 47 },
      { subchapter: "3.3.8", title: "Access from the Highways / Classified Roads", page: 47 },
      { subchapter: "3.3.9", title: "Access Provision for Special Buildings", page: 48 },
      { subchapter: "3.3.10", title: "Cul-de-sacs", page: 48 },
      { subchapter: "3.3.11", title: "Handing Over of Layout Roads", page: 49 },
      { subchapter: "3.3.12", title: "Intersection of Roads", page: 49 },
      { subchapter: "3.3.13", title: "Acute Angled Junctions", page: 49 },
      { subchapter: "3.3.14", title: "Land-locked Plot", page: 49 },
      { subchapter: "3.3.15", title: "Approach by Underpass or Over Bridge for Adjoining Properties", page: 50 },
      { subchapter: "3.4", title: "Recreational Open Spaces", page: 50 },
      { subchapter: "3.4.1", title: "Recreational Open Space", page: 50 },
      { subchapter: "3.4.2", title: "Recreational Open Space - Owner’s Undertaking", page: 51 },
      { subchapter: "3.4.3", title: "Recreational Open Space - Rearrangement", page: 52 },
      { subchapter: "3.4.4", title: "Recreational Open Space - Exclusive", page: 52 },
      { subchapter: "3.4.5", title: "Recreational Open Space in Green Belt", page: 52 },
      { subchapter: "3.4.6", title: "Minimum Dimensions", page: 52 },
      { subchapter: "3.4.7", title: "Structures Permitted in Open Space", page: 52 },
      { subchapter: "3.4.8", title: "Recreational Open Space and Means of Access", page: 53 },
      { subchapter: "3.5", title: "Provision for Amenity Space", page: 53 },
      { subchapter: "3.5.1", title: "Amenity Space in Local Authorities, Special Planning Authorities and Metropolitan Region Authorities", page: 53 },
      { subchapter: "3.5.2", title: "Amenity Space in Regional Plan Areas", page: 54 },
      { subchapter: "3.5.3", title: "Development of Amenity Spaces in Earlier Sanctioned Layout", page: 54 },
      { subchapter: "3.6", title: "Provision for Electric Sub-station", page: 55 },
      { subchapter: "3.7", title: "Minimum Plot Area for Various Uses", page: 55 },
      { subchapter: "3.8", title: "Provision for Inclusive Housing", page: 56 },
      { subchapter: "3.9", title: "Net Plot Area and Computation of FSI", page: 59 },
      { subchapter: "3.10", title: "Transfer of DP Sites (Other than DP Road) in Lieu of FSI", page: 59 },
      { subchapter: "3.11", title: "Relocation of DP-RP Sites / Roads", page: 59 },
      { subchapter: "3.12", title: "Amalgamation of Plots", page: 60 },
      { subchapter: "3.13", title: "Development of Cycle Track Along River and Nallah", page: 60 }
    ]
  },
  {
    chapter: "CHAPTER - 4",
    title: "LAND USE CLASSIFICATION AND PERMISSIBLE USES",
    sections: [
      { subchapter: "4.1", title: "General", page: 61 },
      { subchapter: "4.2", title: "Land Use Classification and Equivalency of Zones", page: 61 },
      { subchapter: "4.3", title: "Residential Zone - R-1", page: 63 },
      { subchapter: "4.4", title: "Residential Zone - R-2", page: 65 },
      { subchapter: "4.5", title: "Low Density Residential Zone", page: 67 },
      { subchapter: "4.6", title: "Future Urbanisable Zone", page: 67 },
      { subchapter: "4.7", title: "Commercial Zone", page: 67 },
      { subchapter: "4.8", title: "Industrial Zone", page: 67 },
      { subchapter: "4.8.1", title: "Allowing Residential / Commercial Uses in Industrial Zone", page: 68 },
      { subchapter: "4.9", title: "Loom Industry cum Residential Zone", page: 71 },
      { subchapter: "4.10", title: "Public / Semi Public Zone", page: 71 },
      { subchapter: "4.11", title: "Agricultural Zone", page: 72 },
      { subchapter: "4.12", title: "Green Belt Zone / River Protection Belt", page: 78 },
      { subchapter: "4.13", title: "Traffic and Transportation Zone", page: 78 },
      { subchapter: "4.14", title: "Regional Park Zone", page: 78 },
      { subchapter: "4.15", title: "Tourism Development Zone", page: 79 },
      { subchapter: "4.16", title: "Afforestation Zone", page: 79 },
      { subchapter: "4.17", title: "Hill Top - Hill Slope Zone / Hilly Area", page: 79 },
      { subchapter: "4.18", title: "Green Zone-2", page: 79 },
      { subchapter: "4.19", title: "Forest Zone", page: 79 },
      { subchapter: "4.20", title: "Defense Zone", page: 79 },
      { subchapter: "4.21", title: "Mines and Quarry Zone", page: 80 },
      { subchapter: "4.22", title: "Public Utility Zone", page: 80 },
      { subchapter: "4.23", title: "Woodland Corridor", page: 80 },
      { subchapter: "4.24", title: "Special Economic Zone", page: 80 },
      { subchapter: "4.25", title: "Airport and Allied Activities / Service Zone", page: 80 },
      { subchapter: "4.26", title: "Additional Uses", page: 81 },
      { subchapter: "4.27", title: "Uses Permissible in Development Plan Reservations", page: 81 }
    ]
  },
  {
    chapter: "CHAPTER - 5",
    title: "ADDITIONAL PROVISIONS FOR REGIONAL PLAN AREAS",
    sections: [
      { subchapter: "5.0", title: "General", page: 85 },
      { subchapter: "5.1", title: "For all Regional Plan Areas", page: 85 },
      { subchapter: "5.1.1", title: "Development Permissible Adjacent to Gaothan", page: 85 },
      { subchapter: "5.1.2", title: "Regulations for Development of Tourist Resorts / Holiday Homes / Township", page: 86 },
      { subchapter: "5.1.3", title: "Committed Development", page: 86 },
      { subchapter: "5.1.4", title: "Rectification of Draftsman's Error", page: 86 },
      { subchapter: "5.1.5", title: "Highways Notified by State / Central Government", page: 87 },
      { subchapter: "5.1.6", title: "Station Area Development", page: 87 },
      { subchapter: "5.1.7", title: "Modification Proposals Already Sanctioned", page: 87 },
      { subchapter: "5.1.8", title: "Provision of Amenity Space", page: 87 },
      { subchapter: "5.1.9", title: "Residential Zone with Payment of Premium", page: 88 },
      { subchapter: "5.2", title: "For Thane - Raigad - Palghar Regional Plan", page: 88 },
      { subchapter: "5.2.1", title: "Development in Tarapur - Boisar Area", page: 88 },
      { subchapter: "5.3", title: "For Ratnagiri - Sindhudurg Regional Plan", page: 89 },
      { subchapter: "5.3.1", title: "Area within Ratnagiri District", page: 89 },
      { subchapter: "5.3.2", title: "Area within Sindhudurg District", page: 89 },
      { subchapter: "5.4", title: "For Kolhapur Regional Plan", page: 91 },
      { subchapter: "5.5", title: "For Satara Regional Plan", page: 92 },
      { subchapter: "5.6", title: "For Hingoli, Buldhana, Washim, Yawatmal, Nanded Regional Plan", page: 101 },
      { subchapter: "5.7", title: "For Raigad Regional Plan", page: 102 },
      { subchapter: "5.8", title: "For Solapur Regional Plan", page: 102 },
      { subchapter: "5.9", title: "For Pune Regional Plan", page: 102 },
      { subchapter: "5.10", title: "Certain Regulations Cease to Operate in Future", page: 104 },
      { subchapter: "5.11", title: "Board of Appeals", page: 104 },
      { subchapter: "5.12", title: "Aurangabad Regional Plan", page: 105 }
    ]
  },
  {
    chapter: "CHAPTER - 6",
    title: "GENERAL BUILDING REQUIREMENTS - SETBACK, MARGINAL DISTANCE, HEIGHT AND PERMISSIBLE FSI",
    sections: [
      { subchapter: "6.0", title: "General", page: 107 },
      { subchapter: "6.1", title: "Regulations for Congested Area", page: 107 },
      { subchapter: "6.1.1", title: "Residential Buildings / Residential Buildings with Mixed-use", page: 107 },
      { subchapter: "6.1.2", title: "Other Buildings like Public / Semi-Public, Educational, Medical, Institutional, etc.", page: 109 },
      { subchapter: "6.1.3", title: "Width of Pathway", page: 109 },
      { subchapter: "6.1.4", title: "Front Setback", page: 109 },
      { subchapter: "6.2", title: "Regulations for Outside Congested Area (Non-Congested Area)", page: 109 },
      { subchapter: "6.2.1", title: "Marginal Distances and Set-back for Residential Buildings", page: 109 },
      { subchapter: "6.2.2", title: "Other Buildings", page: 112 },
      { subchapter: "6.2.3", title: "Marginal Distances for Buildings of Higher Heights", page: 116 },
      { subchapter: "6.2.4", title: "In the Cases of Layouts of Two or More Buildings in a Plot", page: 117 },
      { subchapter: "6.2.5", title: "In Case of Group Housing Scheme", page: 117 },
      { subchapter: "6.2.6", title: "Building Abutting Two or More Streets", page: 117 },
      { subchapter: "6.3", title: "Permissible FSI", page: 117 },
      { subchapter: "6.4", title: "Industrial Buildings", page: 121 },
      { subchapter: "6.5", title: "FSI of Green Belt", page: 121 },
      { subchapter: "6.6", title: "Calculation of Built-up Area for the Purposes of FSI", page: 122 },
      { subchapter: "6.7", title: "Permissible Projections in Marginal Open Spaces / Distances", page: 122 },
      { subchapter: "6.8", title: "Exclusion of Structures / Projections for FSI Calculation", page: 123 },
      { subchapter: "6.9", title: "Interior and Exterior Chowk", page: 124 },
      { subchapter: "6.10", title: "Height of Building", page: 124 },
      { subchapter: "6.11", title: "Height Exemptions", page: 125 },
      { subchapter: "6.12", title: "Requirements in Case of Building more than 70 m. Height", page: 125 },
      { subchapter: "6.13", title: "FSI of Lands Affected by HEMRL or Other Restrictions", page: 125 },
      { subchapter: "6.14", title: "Provision of Recreational Floor", page: 125 }
    ]
  },
  {
    chapter: "CHAPTER - 7",
    title: "HIGHER FSI FOR CERTAIN USES",
    sections: [
      { subchapter: "7.0", title: "General", page: 127 },
      { subchapter: "7.1", title: "Higher F.S.I.", page: 128 },
      { subchapter: "7.2", title: "Entitlement of FSI for Road Widening or Construction of New Roads", page: 131 },
      { subchapter: "7.3", title: "Development / Redevelopment of Staff Quarters", page: 131 },
      { subchapter: "7.4", title: "Development / Redevelopment of Housing Schemes of MHADA", page: 133 },
      { subchapter: "7.5", title: "Protection of FSI in Redevelopment of Existing Buildings", page: 136 },
      { subchapter: "7.6", title: "Redevelopment of Old Dilapidated / Dangerous Buildings", page: 136 },
      { subchapter: "7.6.1", title: "Redevelopment of Multi-dwelling Buildings of Owner / Owners", page: 137 },
      { subchapter: "7.6.2", title: "Redevelopment of Tenanted Buildings", page: 137 },
      { subchapter: "7.7", title: "Development of Housing for EWS / LIG", page: 138 },
      { subchapter: "7.8", title: "Regulations for Development of Information Technology Establishment", page: 139 },
      { subchapter: "7.8.1", title: "For Municipal Corporation, Area Development Authority", page: 139 },
      { subchapter: "7.8.2", title: "For Municipal Council, Nagar Panchayat", page: 141 },
      { subchapter: "7.8.3", title: "For Regional Plan Area", page: 141 },
      { subchapter: "7.9", title: "Regulation for Development of Biotechnology Parks", page: 142 },
      { subchapter: "7.10", title: "Incentive for Green Buildings", page: 143 },
      { subchapter: "7.11", title: "Development of Public Toilet", page: 144 },
      { subchapter: "7.12", title: "Buildings of Smart Fin-Tech Centre", page: 144 },
      { subchapter: "7.13", title: "Commercial Building in CBD, Commercial, Residential Zone", page: 145 }
    ]
  },
  {
    chapter: "CHAPTER - 8",
    title: "PARKING, LOADING AND UNLOADING SPACES",
    sections: [
      { subchapter: "8.1", title: "Parking Spaces", page: 147 },
      { subchapter: "8.2", title: "Off Street Parking Requirement", page: 148 },
      { subchapter: "8.2.1", title: "Off Street Parking Requirement", page: 148 },
      { subchapter: "8.2.2", title: "Off Street Parking Requirement for Various Planning Authorities", page: 154 }
    ]
  },
  {
    chapter: "CHAPTER - 9",
    title: "REQUIREMENTS OF PART OF BUILDING",
    sections: [
      { subchapter: "9.0", title: "Standard Requirement of Various Parts of Buildings", page: 155 },
      { subchapter: "9.1", title: "Plinth", page: 155 },
      { subchapter: "9.2", title: "Habitable Rooms", page: 155 },
      { subchapter: "9.3", title: "Kitchen", page: 156 },
      { subchapter: "9.4", title: "Bath Rooms, Water Closets, Combined Bath Room and Water Closet", page: 156 },
      { subchapter: "9.5", title: "Ledge or Tand / Loft", page: 156 },
      { subchapter: "9.6", title: "Cupboard", page: 157 },
      { subchapter: "9.7", title: "Mezzanine Floor", page: 157 },
      { subchapter: "9.8", title: "Store Room", page: 158 },
      { subchapter: "9.9", title: "Garage", page: 158 },
      { subchapter: "9.10", title: "Roofs", page: 158 },
      { subchapter: "9.11", title: "Basements", page: 159 },
      { subchapter: "9.12", title: "Ramp", page: 160 },
      { subchapter: "9.13", title: "Podium", page: 160 },
      { subchapter: "9.14", title: "Balcony", page: 161 },
      { subchapter: "9.15", title: "Supported Double Height Terraces", page: 161 },
      { subchapter: "9.16", title: "Stilt", page: 161 },
      { subchapter: "9.17", title: "Chimneys", page: 161 },
      { subchapter: "9.18", title: "Letter Box", page: 162 },
      { subchapter: "9.19", title: "Meter Room", page: 162 },
      { subchapter: "9.20", title: "Lighting and Ventilation of Room", page: 162 },
      { subchapter: "9.21", title: "Overhead Tanks", page: 163 },
      { subchapter: "9.22", title: "Parapet", page: 163 },
      { subchapter: "9.23", title: "Cabin", page: 163 },
      { subchapter: "9.24", title: "Wells", page: 163 },
      { subchapter: "9.25", title: "Septic Tanks", page: 163 },
      { subchapter: "9.26", title: "Boundary / Compound Wall", page: 163 },
      { subchapter: "9.27", title: "Provision of Lift", page: 164 },
      { subchapter: "9.28", title: "Exit Requirements", page: 164 },
      { subchapter: "9.29", title: "Other Requirements of Individual Exit at Each Floor", page: 167 },
      { subchapter: "9.30", title: "Architectural Projections", page: 171 },
      { subchapter: "9.31", title: "Additional Requirements in Case of Housing Schemes", page: 171 },
      { subchapter: "9.32", title: "Fire Protection Requirement", page: 171 },
      { subchapter: "9.33", title: "Service Floor", page: 172 }
    ]
  },
  {
    chapter: "CHAPTER - 10",
    title: "CITY SPECIFIC REGULATIONS",
    sections: [
      { subchapter: "10.0", title: "General", page: 173 },
      { subchapter: "10.1", title: "Pune City Municipal Corporation", page: 173 },
      { subchapter: "10.2", title: "Thane Municipal Corporation Area", page: 176 },
      { subchapter: "10.3", title: "Nagpur Municipal Corporation", page: 182 },
      { subchapter: "10.4", title: "Nagpur Metropolitan Region Development Authority", page: 183 },
      { subchapter: "10.5", title: "Nashik Municipal Corporation", page: 186 },
      { subchapter: "10.6", title: "Vasai-Virar City Municipal Corporation", page: 187 },
      { subchapter: "10.7", title: "Mira-Bhayandar Municipal Corporation", page: 187 },
      { subchapter: "10.8", title: "Ulhasnagar City Municipal Corporation", page: 187 },
      { subchapter: "10.9", title: "Kolhapur Municipal Corporation", page: 187 },
      { subchapter: "10.10", title: "Navi Mumbai Municipal Corporation", page: 193 },
      { subchapter: "10.11", title: "National Park and Tungareshwar Eco Sensitive Zone", page: 199 },
      { subchapter: "10.12", title: "Maharashtra Airport Development Company Notified Area", page: 199 },
      { subchapter: "10.13", title: "Bhiwandi Surrounding Notified Area", page: 199 },
      { subchapter: "10.14", title: "CIDCO Area Excluding NAINA Area", page: 203 },
      { subchapter: "10.14 A", title: "CIDCO Area within Panvel Municipal Corporation", page: 205 },
      { subchapter: "10.15", title: "Certain Regulations Cease to Operate in Future", page: 205 }
    ]
  },
  {
    chapter: "CHAPTER - 11",
    title: "ACQUISITION AND DEVELOPMENT OF RESERVED SITES IN DEVELOPMENT PLANS",
    sections: [
      { subchapter: "11.0", title: "General", page: 207 },
      { subchapter: "11.1", title: "Manner of Development of Reserved Site in Development Plan", page: 207 },
      { subchapter: "11.2", title: "Regulations for Grant of Transferable Development Rights", page: 221 },
      { subchapter: "11.2.1", title: "Transferable Development Rights", page: 221 },
      { subchapter: "11.2.2", title: "Cases Eligible for Transferable Development Rights", page: 221 },
      { subchapter: "11.2.3", title: "Cases Not Eligible for Transferable Development Rights", page: 221 },
      { subchapter: "11.2.4", title: "Generation of the Transferable Development Rights", page: 222 },
      { subchapter: "11.2.5", title: "Transferable Development Rights against Construction of Amenity", page: 223 },
      { subchapter: "11.2.6", title: "Utilisation of Transferable Development Rights", page: 224 },
      { subchapter: "11.2.7", title: "Utilisation of Transferable Development Rights and Road Width Relation", page: 224 },
      { subchapter: "11.2.8", title: "Areas Restricted from Utilisation of Transferable Development Rights", page: 224 },
      { subchapter: "11.2.9", title: "General Stipulation", page: 225 },
      { subchapter: "11.2.10", title: "Transfer of DRC", page: 225 },
      { subchapter: "11.2.11", title: "Infrastructure Improvement Charges", page: 226 },
      { subchapter: "11.2.12", title: "Vesting of Land", page: 226 },
      { subchapter: "11.2.13", title: "Effect of this Regulation", page: 226 },
      { subchapter: "11.3", title: "Reservation Credit Certificate (RCC)", page: 226 }
    ]
  },
  {
    chapter: "CHAPTER - 12",
    title: "STRUCTURAL SAFETY, WATER SUPPLY, DRAINAGE AND SANITARY REQUIREMENTS, OUTDOOR DISPLAY AND OTHER SERVICES",
    sections: [
      { subchapter: "12.1", title: "Structural Design", page: 229 },
      { subchapter: "12.2", title: "Quality of Materials and Workmanship", page: 229 },
      { subchapter: "12.3", title: "Alternative Materials, Methods of Design & Construction and Tests", page: 229 },
      { subchapter: "12.4", title: "Building Services", page: 230 },
      { subchapter: "12.5", title: "Water Supply, Drainage and Sanitary Requirements", page: 230 },
      { subchapter: "12.6", title: "Drainage and Sanitation Requirements", page: 232 },
      { subchapter: "12.6.1", title: "General", page: 232 },
      { subchapter: "12.6.2", title: "For Residences", page: 232 },
      { subchapter: "12.6.3", title: "For Buildings Other Than Residences", page: 232 },
      { subchapter: "12.7", title: "Signs and Outdoor Display Structures", page: 233 }
    ]
  },
  {
    chapter: "CHAPTER - 13",
    title: "SPECIAL PROVISIONS FOR CERTAIN BUILDINGS",
    sections: [
      { subchapter: "13.0", title: "General", page: 239 },
      { subchapter: "13.1", title: "Provisions for Barrier Free Access", page: 239 },
      { subchapter: "13.1.1", title: "Definitions", page: 239 },
      { subchapter: "13.1.2", title: "Scope", page: 239 },
      { subchapter: "13.1.3", title: "Site Development", page: 239 },
      { subchapter: "13.1.4", title: "Building Requirements", page: 240 },
      { subchapter: "13.2", title: "Installation of Solar Assisted Water Heating System / Roof Top Photovoltaic System", page: 242 },
      { subchapter: "13.3", title: "Rain Water Harvesting", page: 243 },
      { subchapter: "13.4", title: "Grey Water Recycling and Reuse", page: 244 },
      { subchapter: "13.5", title: "Solid Waste Management", page: 246 }
    ]
  },
  {
    chapter: "CHAPTER - 14",
    title: "SPECIAL SCHEMES",
    sections: [
      { subchapter: "14.1", title: "Integrated Township Project (ITP)", page: 247 },
      { subchapter: "14.1.1", title: "For Regional Plan Area", page: 247 },
      { subchapter: "14.1.2", title: "For Development Plan Area", page: 263 },
      { subchapter: "14.2", title: "Transit Oriented Development (TOD)", page: 264 },
      { subchapter: "14.2.1", title: "For Pune Municipal Corporation Area", page: 265 },
      { subchapter: "14.2.2", title: "Pune Metropolitan Region Development Authority Area", page: 269 },
      { subchapter: "14.2.3", title: "For Nagpur Municipal Corporation and Nagpur Metropolitan Region", page: 269 },
      { subchapter: "14.2.4", title: "For Other Municipal Corporations and Other Metropolitan Regions", page: 274 },
      { subchapter: "14.2.5", title: "Regulations for BRT Corridor in Pimpri-Chinchwad", page: 274 },
      { subchapter: "14.3", title: "Affordable Housing Scheme", page: 275 },
      { subchapter: "14.4", title: "Pradhan Mantri Awas Yojana", page: 278 },
      { subchapter: "14.4.1", title: "For Development Plan Area", page: 278 },
      { subchapter: "14.4.2", title: "For Regional Plan Area", page: 279 },
      { subchapter: "14.5", title: "Conservation of Heritage Buildings / Precincts / Natural Features", page: 279 },
      { subchapter: "14.6", title: "Slum Rehabilitation Scheme for Pune, PCMC, PCNTDA and Nagpur", page: 285 },
      { subchapter: "14.7", title: "Slum Rehabilitation Scheme for Other Municipal Corporations", page: 318 },
      { subchapter: "14.8", title: "Urban Renewal Scheme", page: 332 },
      { subchapter: "14.9", title: "Development of Tourism and Hospitality Services under Community Nature Conservancy", page: 349 },
      { subchapter: "14.10", title: "Integrated Information Technology Township (IITP)", page: 350 },
      { subchapter: "14.11", title: "Integrated Logistic Park (ILP)", page: 354 },
      { subchapter: "14.12", title: "Industrial Township Under Aerospace and Defense Manufacturing Policy", page: 357 },
      { subchapter: "14.13", title: "Development of Integrated Industrial Area", page: 357 }
    ]
  },
  {
    chapter: "CHAPTER - 15",
    title: "REGULATIONS FOR SPECIAL ACTIVITIES / PLANS",
    sections: [
      { subchapter: "15.1", title: "Quarrying Operations", page: 359 },
      { subchapter: "15.2", title: "Erection of Mobile Towers", page: 359 },
      { subchapter: "15.3", title: "Preparation of Local Area Plan", page: 360 },
      { subchapter: "15.4", title: "Guidelines for Street Design in City / Town", page: 360 }
    ]
  }
];


const appendix = [
  {
    no: '01',
    title: 'Appendix A-1',
  },
  {
    no: '02',
    title: 'Appendix A-2',
  },
  {
    no: '03',
    title: 'Appendix B',
  },
  {
    no: '04',
    title: 'Appendix C',
  },
  {
    no: '05',
    title: 'Appendix D-1',
  },
  {
    no: '06',
    title: 'Appendix D-2',
  },
  {
    no: '07',
    title: 'Appendix D-3',
  },
  {
    no: '08',
    title: 'Appendix E-1',
  },
  {
    no: '09',
    title: 'Appendix E-2',
  },
  {
    no: '10',
    title: 'Appendix F',
  },
  {
    no: '11',
    title: 'Appendix G',
  },
  {
    no: '12',
    title: 'Appendix H',
  },
  {
    no: '13',
    title: 'Appendix I',
  },
  {
    no: '14',
    title: 'Appendix J',
  },
  {
    no: '15',
    title: 'Appendix K',
  },
  {
    no: '16',
    title: 'Appendix K-1',
  },
  {
    no: '17',
    title: 'Appendix K-2',
  },
  {
    no: '18',
    title: 'Appendix L',
  },
  {
    no: '19',
    title: 'Appendix M',
  },
  {
    no: '20',
    title: 'Form giving Particulars of Development (Item iv of Appendix A -1)',
  },
  {
    no: '21',
    title: 'Form giving Particulars of Development (Part of Appendix A -2, Item 6)',
  },
  {
    no: '22',
    title: 'Form of Statement 1+2+3',
  },
  {
    no: '23',
    title: 'Proforma - I Area Statement',
  }
];

export { formDataSchema, districts, formParkingSchema, formPotentialFsiSchema, formBuildingMarginSchema, udcprIndex, appendix };
